apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
data:
  otel-collector-config.yaml: |-
    {
      receivers:
        otlp:
          protocols:
            grpc:
      exporters:
        prometheus:
          endpoint: "0.0.0.0:8889"
      processors:
        batch:
      service:
        pipelines:
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [prometheus]
    }
